AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: >
  ${AWS::StackName}

  SAM Template for Serverless Q&A chatbot
# A description of the template's purpose: setting up a serverless Q&A chatbot.

Globals:
  Function:
    Runtime: python3.11
    # Defines the Python runtime version for all Lambda functions in this template.
    Handler: main.lambda_handler
    # The method within your code that processes events.
    Architectures:
      - arm64
    # Specifies the architecture type for the Lambda functions (ARM64).
    Tracing: Active
    Environment:
      Variables:
        LOG_LEVEL: INFO
    # Environment variables accessible from the function code.
    Layers:
      - !Sub arn:aws:lambda:${AWS::Region}:017000801446:layer:AWSLambdaPowertoolsPythonV2-Arm64:51
    # Specifies a Lambda layer to use with the function.

Parameters:
  Frontend:
    Default: local
    Type: String
    AllowedValues:
      - local
      - amplify
    # Parameter for specifying the frontend deployment type with allowed values.
  Repository:
    Type: String
    # Parameter for specifying the code repository.

Conditions:
  DeployToAmplifyHosting: !Equals
    - !Ref Frontend
    - amplify
    # Condition to check if the deployment should be on AWS Amplify Hosting.

Resources:
  DocumentBucket:
    Type: "AWS::S3::Bucket"
    # Resource type (Amazon S3 bucket).
    Properties:
      BucketName: !Sub "my-app-${AWS::StackName}-${AWS::Region}-${AWS::AccountId}"
      # Sets a unique name for the S3 bucket using substitution variables.
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - HEAD
              - POST
              - DELETE
            AllowedOrigins:
              - "*"
      # Configures CORS to allow all origins and a set of HTTP methods.
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    # Blocks public access to the bucket.

  DocumentBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    # Resource type (Amazon S3 bucket policy).
    Properties:
      PolicyDocument:
        Id: EnforceHttpsPolicy
        Version: "2012-10-17"
        Statement:
          - Sid: EnforceHttpsSid
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub "arn:aws:s3:::${DocumentBucket}/*"
              - !Sub "arn:aws:s3:::${DocumentBucket}"
            Condition:
              Bool:
                "aws:SecureTransport": "false"
      # Policy to deny all actions on the bucket if the request is not using HTTPS.
      Bucket: !Ref DocumentBucket
    # Associates the policy with the specified S3 bucket.

  DocumentTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      KeySchema:
        - AttributeName: userid
          KeyType: HASH
        - AttributeName: documentid
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: userid
          AttributeType: S
        - AttributeName: documentid
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    # Defines a DynamoDB table for documents with specific attributes and throughput settings.

  ConversationTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      KeySchema:
        - AttributeName: userid
          KeyType: HASH
        - AttributeName: conversationid
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: userid
          AttributeType: S
        - AttributeName: conversationid
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
    # Defines a DynamoDB table for conversations with a pay-per-request billing mode.

  ConversationHistoryTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      KeySchema:
        - AttributeName: UserId
          KeyType: HASH
        - AttributeName: ConversationId
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: UserId
          AttributeType: S
        - AttributeName: ConversationId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
    # Another DynamoDB table for storing conversation history, also using pay-per-request billing.

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
    # Configures an Amazon Cognito user pool with specific attributes and policies for user management.

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ClientName: !Ref CognitoUserPool
      GenerateSecret: false
    # Defines a client for the Cognito user pool to interact with other services.

  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt CognitoUserPool.Arn
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'*'"
        AllowMethods: "'*'"
    # Defines a serverless API gateway with CORS and authorization settings.

  GeneratePresignedUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/generate_presigned_url/
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref DocumentBucket
      Environment:
        Variables:
          BUCKET: !Ref DocumentBucket
          REGION: !Sub ${AWS::Region}
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /generate_presigned_url
            Method: GET
    # Lambda function to generate presigned URLs for S3, allowing temporary access to objects.

  UploadTriggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/upload_trigger/
      Timeout: 10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DocumentTable
        - S3ReadPolicy:
            BucketName: !Sub "my-app-${AWS::StackName}-${AWS::Region}-${AWS::AccountId}*"
        - Statement:
            - Sid: "AllowS3HeadObject"
              Effect: "Allow"
              Action:
                - "s3:HeadObject"
              Resource: !Sub "arn:aws:s3:::my-app-${AWS::StackName}-${AWS::Region}-${AWS::AccountId}*/*"
            - Sid: "BedrockKnowledgeBase"
              Effect: "Allow"
              Action:
                - "bedrock:StartIngestionJob"
              Resource: !Sub "arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:knowledge-base/*"
            - Sid: "SSMParameterAccess"
              Effect: "Allow"
              Action:
                - "ssm:GetParameter"
              Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/*"
      Environment:
        Variables:
          DOCUMENT_TABLE: !Ref DocumentTable
          BUCKET: !Sub "my-app-${AWS::StackName}-${AWS::Region}-${AWS::AccountId}"
          KNOWLEDGE_BASE_DETAILS_SSM_PATH: !Sub "{{resolve:ssm:/${AWS::StackName}/knowledge-base:1}}"
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref DocumentBucket
            Events:
              - s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .pdf
    # Lambda function triggered by S3 events (e.g., file uploads), with permissions to interact with DynamoDB and S3.

  GetDocumentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/get_document/
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref DocumentTable
      Environment:
        Variables:
          DOCUMENT_TABLE: !Ref DocumentTable
          KNOWLEDGE_BASE_DETAILS_SSM_PATH: !Sub "{{resolve:ssm:/${AWS::StackName}/knowledge-base:1}}"
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /users/{user_id}/documents/{documentid}
            Method: GET
    # Lambda function to retrieve a specific document from DynamoDB, exposed via an API endpoint.

  GetAllDocuments:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/get_all_documents/
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref DocumentTable
      Environment:
        Variables:
          DOCUMENT_TABLE: !Ref DocumentTable
          KNOWLEDGE_BASE_DETAILS_SSM_PATH: !Sub "{{resolve:ssm:/${AWS::StackName}/knowledge-base:1}}"
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /users/{user_id}/documents
            Method: GET
    # Lambda function to retrieve all documents from DynamoDB, exposed via an API endpoint.

  GetConversations:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/get_conversations/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ConversationTable
      Environment:
        Variables:
          CONVERSATION_TABLE: !Ref ConversationTable
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /users/{user_id}/conversations
            Method: GET
    # Lambda function to retrieve all conversations from DynamoDB, exposed via an API endpoint.

  GetConversation:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/get_conversation/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ConversationTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ConversationHistoryTable
      Environment:
        Variables:
          CONVERSATION_TABLE: !Ref ConversationTable
          CONVERSATION_HISTORY_TABLE: !Ref ConversationHistoryTable
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /users/{user_id}/conversations/{conversationid}
            Method: GET
    # Lambda function to retrieve a specific conversation from DynamoDB, exposed via an API endpoint.

  AddConversationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/add_conversation/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ConversationTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ConversationHistoryTable
      Environment:
        Variables:
          CONVERSATION_TABLE: !Ref ConversationTable
          CONVERSATION_HISTORY_TABLE: !Ref ConversationHistoryTable
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /users/{user_id}/conversations
            Method: POST
    # Lambda function to add a new conversation to DynamoDB, exposed via an API endpoint.

  GenerateResponseFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/generate_response/
      Timeout: 30
      MemorySize: 2048
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ConversationHistoryTable
        - SSMParameterReadPolicy:
            ParameterName: !Sub "{{resolve:ssm:/${AWS::StackName}/knowledge-base:1}}"
        - Statement:
            - Sid: "BedrockModel"
              Effect: "Allow"
              Action:
                - "bedrock:InvokeModel"
                - "bedrock:InvokeModelWithResponseStream"
              Resource:
                - "arn:aws:bedrock:*::foundation-model/mistral.mistral-7b-instruct-v0:2"
            - Sid: "BedrockKnowledgeBase"
              Effect: "Allow"
              Action:
                - "bedrock:Retrieve"
              Resource: !Sub "arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:knowledge-base/*"
      Environment:
        Variables:
          CONVERSATION_HISTORY_TABLE: !Ref ConversationHistoryTable
          KNOWLEDGE_BASE_DETAILS_SSM_PATH: !Sub "{{resolve:ssm:/${AWS::StackName}/knowledge-base:1}}"
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /users/{user_id}/conversations/{conversationid}/response
            Method: POST
    # Lambda function to generate a response for a conversation using a machine learning model, exposed via an API endpoint.

  AmplifyApp:
    Type: AWS::Amplify::App
    Condition: DeployToAmplifyHosting
    Properties:
      Name: !Sub "${AWS::StackName}-${AWS::Region}-${AWS::AccountId}"
      Repository: !Ref Repository
      BuildSpec: |
        version: 1
        applications:
          - frontend:
              phases:
                preBuild:
                  commands:
                    - npm ci
                build:
                  commands:
                    - npm run build
              artifacts:
                baseDirectory: dist
                files:
                  - '**/*'
              cache:
                paths:
                  - node_modules/**/*
            appRoot: frontend
      AccessToken: !Sub "{{resolve:secretsmanager:github-access-token:SecretString}}"
      EnvironmentVariables:
        - Name: AMPLIFY_MONOREPO_APP_ROOT
          Value: frontend
        - Name: VITE_REGION
          Value: !Ref AWS::Region
        - Name: VITE_API_ENDPOINT
          Value: !Sub "https://${Api}.execute-api.${AWS::Region}.${AWS::URLSuffix}/dev/"
        - Name: VITE_USER_POOL_ID
          Value: !Ref CognitoUserPool
        - Name: VITE_USER_POOL_CLIENT_ID
          Value: !Ref CognitoUserPoolClient
    # Configures an AWS Amplify app with environment variables and build settings for a frontend hosted on Amplify.

  AmplifyBranch:
    Type: AWS::Amplify::Branch
    Condition: DeployToAmplifyHosting
    Properties:
      BranchName: main
      AppId: !GetAtt AmplifyApp.AppId
      EnableAutoBuild: true
    # Defines a branch for the Amplify app which auto-builds when changes are pushed.

Outputs:
  CognitoUserPool:
    Value: !Ref CognitoUserPool
  CognitoUserPoolClient:
    Value: !Ref CognitoUserPoolClient
  ApiGatewayBaseUrl:
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.${AWS::URLSuffix}/dev/"
  KnowledgeBaseDetails:
    Description: "Details of the Knowledge Base"
    Value: !Sub "{{resolve:ssm:/${AWS::StackName}/knowledge-base:1}}"
